---
- name: Install Python 3
  apt:
    name: python3
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install boto3 using pip3
  become: true
  pip:
    name: boto3
    state: present

- name: Install AWS CLI using pip
  become: true
  pip:
    name: awscli
    state: latest
    executable: pip3

- name: Install Ansible
  pip:
    name: ansible
    state: latest
    
- name: Download HashiCorp GPG key
  become: yes
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.gpg
    mode: '0644'

- name: Add HashiCorp GPG key to keyring
  become: yes
  command: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp.gpg

- name: Add HashiCorp APT repository
  become: yes
  lineinfile:
    path: /etc/apt/sources.list.d/hashicorp.list
    line: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    create: yes

- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: Install Terraform
  apt:
    name: terraform
    state: present

- name: Install Packer
  apt:
    name: packer
    state: present



